language: android
android:
  components:
    - build-tools-21.0.1
    - android-15

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script:
  ./gradlew build